# Generated by Django 5.2.1 on 2025-06-05 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('mobile', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('sslc_mark', models.FloatField()),
                ('puc_mark', models.FloatField()),
                ('father_mobile', models.CharField(max_length=15)),
                ('mother_mobile', models.CharField(max_length=15)),
                ('semester_card', models.FileField(blank=True, null=True, upload_to='semester_cards/')),
                ('disability', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True, null=True)),
                ('accommodation', models.CharField(choices=[('Hostel', 'Hostel'), ('Travel', 'Travel')], max_length=10)),
                ('college_fee_demand', models.FloatField()),
                ('college_fee_balance', models.FloatField()),
                ('hostel_fee_demand', models.FloatField()),
                ('hostel_fee_balance', models.FloatField()),
                ('bus_fee_demand', models.FloatField()),
                ('bus_fee_balance', models.FloatField()),
                ('achievement_status', models.BooleanField(default=False)),
                ('aicte_points', models.IntegerField()),
                ('scholarship_status', models.BooleanField(default=False)),
                ('scholarship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance', models.FloatField()),
                ('ia_marks', models.FloatField()),
                ('timetable', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('circulars', models.TextField(blank=True, null=True)),
                ('parents_visits', models.TextField(blank=True, null=True)),
                ('participation_permission', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
