# Generated by Django 5.1.6 on 2025-06-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='travel_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
