# Generated by Django 5.1.6 on 2025-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_travel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievement_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
